SpellActivationOverlay.lua, changelog.md, classes/common.lua
Fix for #7 with the following solution:
- a new param can be passed when activating a SAO, to force-play a pulse effect
- by default this param is false
- this param is set if and only when gaining/losing stacks of an existing effect
- this param is *not* set when starting stacks (i.e., from 0 to 1) or when losing them all (i.e., from _n_ to 0)
=> Fix of #7 Pulse Stop

SpellActivationOverlay.lua, classes/common.lua, classes/deathknight.lua, classes/druid.lua, classes/hunter.lua, classes/mage.lua, classes/paladin.lua, classes/priest.lua, classes/shaman.lua, classes/warlock.lua, classes/warrior.lua
Implementation of #8
- new parameter when activating a SAO, to tell if it should pulse
- this param is almost always true, which is equivalent to the previous behaviour
- this param is false in the following cases, which act as a "soon" indicator:
- Mage's Heating Up
- Shaman's Maelstrom Weapon between 1 and 4 stacks (max stacks = 5)
=> Feature #8 Optional Pulse

SpellActivationOverlay.lua, SpellActivationOverlay.xml, changelog.md
Implements #10
- by default, alpha is 50%
- when entering combat, alpha quickly rises to 100%
- when leaving combat, alpha dims back to 50%
Because SAOs usually proc in combat, the default 50% alpha is unnoticeable for most classes.
=> Feature #10 Out of Combat Visibility

changelog.md, classes/common.lua
Fixes #25
The chosen solution was to test if an aura is present immediately after registration.
The only thing to be careful is that the number of stacks of the current buff must match with the number of stacks of the registered aura.
=> Fix #25 Hidden SAOs on ReloadUI

changelog.md, classes/mage.lua
Fixes #36
The code which tracked `UNIT_DIED` is simply commented.
The code is kept in case observed behaviour is a bug that Blizzard decides to fix in the future, in which case we'll simply have to un-comment this code.
=> Fix #36 Heating Up is lost on death

SpellActivationOverlay.lua
Fixes #40
- Entering combat cancels animation of leaving combat
- Leaving combat cancels animation of entering combat
=> Fix #40 Perma dim

.vscode/settings.json, SpellActivationOverlay.lua, SpellActivationOverlay.toc, _curse/release_notes.html, aura.lua, changelog.md, classes/deathknight.lua, classes/druid.lua, classes/hunter.lua, classes/mage.lua, classes/paladin.lua, classes/priest.lua, classes/rogue.lua, classes/warlock.lua, classes/warrior.lua, counter.lua, events.lua, glow.lua, overlay.lua, spell.lua, util.lua
Generalization of Glowing Action Buttons, mainly to Spell Activation Overlays, but not always:
- many SAOs have a natural tendency to use GABs e.g., Hot Streak (Mage) craves for a glowing Pyroblast button
- a few SAOs can’t really use GABs e.g., Omen of Clarity (Druid) could make all buttons glow, which loses the value of showing "cast this spell"
- sometimes SAOs have nothing to do with GABs e.g., Overpower (Warrior) doesn’t have a SAO but it makes sens to glow the Overpower button
=> Glowing Action Buttons (GABs)

SpellActivationOverlay.lua, SpellActivationOverlay.toc, SpellActivationOverlay.xml, changelog.md, components/glow.lua, options/InterfaceOptionsPanels.lua, options/InterfaceOptionsPanels.xml, options/db.lua, options/variables.lua
An options panel is displayed in Interface > AddOns > SpellActivationOverlay
Current options are:
- Spell Alert opacity
- the value is either 0 (off) or between 50% and 100%
- this is consistent with Retail's options for Spell Alerts
- Spell Alert scale factor
- between 25% (4x smaller) and 250% (2.5x bigger)
- Spell Alert offset
- between -200 pixels (almost no offset) and +400 pixels (wide gap)
- Glowing Buttons checkbox
- simply an on/off switch
Spell Alerts can be tested interactively thanks to the "Toggle Test" button.
Please note: if Spell Alerts or Glowing Buttons are already displayed when changing these options, the Spell Alerts and Glowing Buttons may keep their old appearance until next time they are triggered.
=> Options Panel

SpellActivationOverlay.lua, SpellActivationOverlay.toc, changelog.md, components/counter.lua, components/glow.lua, options/InterfaceOptionsPanels.lua, options/InterfaceOptionsPanels.xml
Squashed many bugs with Glowing Action Buttons.
The most visible fix is that buttons should now glow with UI managers, such as Bartender, ElvUI or Dominos.
- Dominos are compatible with Blizzard action buttons, thus they use "Blizzard Glow"
- Bartender uses the "Blizzard Glow" by default
- ElvUI uses the "Pixel Glow" by default
=> Fix #11 Glowing Buttons

components/counter.lua
Checks if the player is under the GCD. Counter spells that are usable keep glowing in that case. It stops glowing if the spell enters on CD.
I've tested this with Riposte. It stops glowing after the spell is used.
Execute keeps glowing after being used and regardless of whether the GCD is active.
This should fix #54.
=> Makes button glow during GCD. Doesn't glow if spell is on CD

components/counter.lua
On the current version, counter spells (e.g. Execute or Overpower) stop and restart glowing depending on whether the player has enough resources to cast them. This behavior is inconsistent with spell overlay effects (e.g. Exorcism or Flash Light because of Art of War), which keep glowing regardless of player resources.
With this PR, counter spells mimic the behavior of spells with overlay, glowing regardless of current mana, rage or energy.
This can be done tanks to another return parameter of [IsUsableSpell](https://wowpedia.fandom.com/wiki/API_IsUsableSpell)
=> Non-mana counter spells glow when they aren't usable because of low resources

changelog.md, components/counter.lua
In theory, GetSpellPowerCost should always return something if the spell is learned. But for some reason, the function sometimes returns "no value" during the loading screen.
Because of this, the player may see a Lua error at the end of a loading screen e.g., when leaving a battleground.
This Pull Request handles this case by simply offering an empty table to `ipairs` when the function returns "no value".
=> GetSpellPowerCost may return "no value"

SpellActivationOverlay.lua, changelog.md, components/events.lua
Register to the LOADING_SCREEN_DISABLED event and remove all SAOs and GABs attached to a buff if the buff is not present after loading.
This solution is very simple and efficient, but at a cost: it assumes the spellID refers to an actual aura, which is not always true.
In practice, this should not be a big problem because:
- most "auras" have an actual aura which matches their respective spellID
- loading screens occurs after e.g., transportation, hearthstone, etc., where procs are rarely needed immediately
- this affects only a handful of "fake auras", namely Heating Up and many druid effects
- this also affects aura testing in options panel ("Toggle Test" button) but it should be marginally problematic
=> Remove SAO/GAB if effect is absent after loading

SpellActivationOverlay.lua, SpellActivationOverlay.toc, SpellActivationOverlay.xml, changelog.md
The 3 steps are:
1. from alpha=100% to alpha=50% in 0.2 seconds (current behavior)
2. then don't do anything for 27.8 seconds
3. then, from alpha=50% to alpha=0% in 2 seconds (new)
This means the effect quickly dims when out of combat, then doesn't change for a while, and then slowly fades out. All steps combined will happen in a total of 30 seconds (0.2+27.8+2 = 30).
Because all steps are performed by the XML schema, this feature should have zero impact on the animation stability or performance.
Because effects normally don't last for more than 30 seconds, this fade-out should be seen only by Fire mages with the Heating Up effect, which has an infinite duration.
=> Out-of-combat has 3 steps, down to alpha=0%

SpellActivationOverlay.toc, changelog.md, components/glow.lua
The Lua error occurred in GetGlowID which, in fact, was internally LibActionButton's GetSpellId which then called GetActionInfo with the wrong arguments.
It's unsure whether the error is a misuse of LibActionButton or if LibActionButton should be safer, but we can prevent this on our side, so let's do it.
Fixes #82.
=> GetGlowID in vehicle

changelog.md, classes/paladin.lua
Uses the same texture as Art of War with 2 talent points, but smaller SAO does not pulse.
GABs are the same as Art of War with 2 talent points.
Fixes #81.
=> SAO/GAB for Art of War with 1 talent point

.vscode/settings.json, SpellActivationOverlay.toc, changelog.md, components/glow.lua
Due to recent changes of ElvUI, side effects made almost impossible to get glowing buttons for ElvUI users, and sometimes spell alerts too.
Fixes #105.
=> ElvUI 13 regression

.vscode/settings.json, SpellActivationOverlay.toc, changelog.md, components/glow.lua, options/db.lua
Detects addons with too old version of LibButtonGlow, and prevent usage of glowing buttons to prevent issues.
=> Azilroka Ulduar

.vscode/settings.json, classes/mage.lua, options/defaults.lua, options/overlayoptions.lua
New option to have the possibility to display both the Heating Up and Hot Streak effects at the same time.
It was already tracked internally, but not displayed to match Retail's behavior. After careful consideration and after hearing feedback from fellow mages, it is now added as an option, disabled by default.
=> Hot Streak Heating Up

changelog.md, classes/druid.lua, classes/mage.lua, components/counter.lua, components/events.lua, components/glow.lua, components/spell.lua, components/util.lua
The `local` keyword allows to transform _farcall_ functions to non-far calls.
It allegedly optimize calls that happen frequently.
=> Optimize frequents calls as 'local'

.vscode/settings.json, changelog.md, classes/mage.lua
Fixes #111.
The Heating Up effect is now hidden and restored when switching back and forth a Fire spec
- when losing the Hot Streak talent while Heating Up is active, the Heating Up effect is banked and hidden for the time being
- when gaining the Hot Streak talent after having banked Heating Up, the Heating Up effect is restored
=> Heating Up after respec

.vscode/settings.json, _curse/release_notes.html, changelog.md, classes/warlock.lua, options/defaults.lua
Implements and closes #95.
New option for Warlocks: glowing button for Drain Soul when the target has 25% health or less.
This option is available in Wrath Classic only, because the damage bonus of Drain Soul on low health enemies was introduced in Wrath of the Lich King.
=> Drain Soul execute

changelog.md, classes/warrior.lua, components/util.lua, options/defaults.lua
Overpower button now also glows while the warrior is under the effect of the Taste for Blood buff. Implements #104, at least partially.
Also fixes a bug that was probably there already, which caused the Overpower glowing button to stay glowing for longer than intended. Fixes #138.
=> Taste for Blood

.vscode/settings.json, SpellActivationOverlay.toc, changelog.md, classes/druid.lua, classes/paladin.lua, classes/priest.lua, classes/shaman.lua, components/item.lua, options/defaults.lua
Add Soul Preserver options for each class. Implements #94 and beyond. Extends #97 which was a fair attempt, although limited to druids and hardcoded.
=> Soul Preserver

SpellActivationOverlay.toc, changelog.md, components/rune.lua
Runes are also checked every 10 secs, to detect them sooner
=> Rune detection should no longer fail

classes/mage.lua
Adds support for Arcane Barrage in SoD.
Adds a blue "Arcane Missiles" texture between the textures for 1-3 stacks and 4 stacks.
=> Support Arcane Barrage in SoD

classes/shaman.lua
The last PR caused a regression towards Elemental Focus and Power Surge preview from options panel.
=> Fix Shaman options

_script/package.sh, classes/warrior.lua
Made changes to warrior.lua and package.sh to add support for Blood Surge procs in Season of Discovery.
In Game Screenshots...
1. ...of the addon configuration UI:
2. ...of the aura:
3. ...of the icon glow: 
4. ...of the console debug log output:
=> Adding support for Blood Surge in Season of Discovery

.vscode/settings.json, SpellActivationOverlay.toc, changelog.md, classes/mage.lua, classes/priest.lua, classes/shaman.lua, components/rune.lua, components/util.lua, options/defaults.lua, options/overlayoptions.lua, textures/texname.lua
Follow-up of #196
- fixed a mistake that caused a Lua error for shamans
- fixed an issue that caused the overlay to sometimes not pulse when it should
- Rolling Thunder variables have been renamed and are initialized slightly differently
- now we make sure `SPELLS_CHANGED` is only used when the Rolling Thunder handler is initialized
- improve code maintainability
- describe changes to Changelog
=> Rolling Thunder followup

changelog.md, classes/priest.lua, options/defaults.lua
Implements #222.
Also cleans Wrath and TBC conditions for Priests, and implements Surge of Light for Cataclysm.
=> Mind Spike (SoD)

.vscode/settings.json, SpellActivationOverlay.lua, SpellActivationOverlay.xml, changelog.md, classes/mage.lua, components/aura.lua, components/events.lua, components/util.lua, options/InterfaceOptionsPanels.xml, options/classoptions.lua, options/variants.lua
Main focus on Mage for Cataclysm. This class was the first to support Cataclysm, and did not get much love since then.
Fixes #257.
Fixes #250.
Fixes #240.
Fixes #288 (or at least, greatly improves it).
Fixes #285 (or at least, greatly improves it).
=> Cataclysm Mage follow-up

classes/hunter.lua
overlay config table was using the wrong number of aura stacks - the proc aura doesn't have stacks
after reaching 5 stacks of ["Ready, Set, Aim..."](https://www.wowhead.com/cata/spell=82925/ready-set-aim) the aura is removed and replaced with a single stack of ["Fire!"](https://www.wowhead.com/cata/spell=82926/fire)
=> fix: show master marksman proc overlay

.vscode/settings.json, SpellActivationOverlay.lua, _script/package.sh, changelog.md, classes/deathknight.lua, classes/druid.lua, classes/hunter.lua, classes/mage.lua, classes/priest.lua, classes/rogue.lua, classes/shaman.lua, classes/warlock.lua, classes/warrior.lua, components/counter.lua, components/project.lua, components/shutdown.lua, components/util.lua, options/defaults.lua, options/glowoptions.lua, options/overlayoptions.lua, options/variants.lua, textures/texname.lua, variables/talent.lua
Introduces the Mists of Pandaria flavor.
The talent system, especially the talent 'variable', has been reworked in accordance with Mists of Pandaria's Talent rework i.e. players now have a specialization, and the talent tree has been replaced by a table table / talent grid.
A few class effects have been supported for testing purposes, but this Pull Request is definitely not an exhaustive support for all classes.
A new concept 'Disabled Class' has been added to indicate classes that have been temporarily disabled, as opposed to 'Unsupported Class' which represents classes without any support whatsoever. Many classes have been flagged as Disabled for Mists of Pandaria. As of today, the only class flagged as Unsupported is the Monk class.
=> Mists of Pandaria
