- classes/deathknight.lua
- classes/mage.lua
- classes/paladin.lua
- classes/priest.lua
- classes/shaman.lua
- classes/warrior.lua
> Feature #16 Cleanup texture names

- classes/hunter.lua
- classes/paladin.lua
- classes/warrior.lua
Added HoW, Execute, Victory Rush and Kill shot
> Added more spells

- changelog.md
- classes/mage.lua
Implements #60.
See issue details for more information about decisions that have been taken.
> Feature #60 Firestarter

- _curse/release_notes.html
- changelog.md
- classes/warlock.lua
Implement Decimation SAO and update Molten Core SAO to avoid conflicts in the Top location
> Decimation

- .vscode/settings.json
- changelog.md
- classes/rogue.lua
- components/counter.lua
- components/spell.lua
Implements https://github.com/ennvina/spellactivationoverlay/issues/56#issuecomment-1238699983
Tested initially with Rogue's Riposte.
> Talented Counters

- SpellActivationOverlay.xml
- changelog.md
- components/overlay.lua
Fixes a bug discovered recently because it became extremely visible. But it was here for a long time. It was just almost invisible.
> Infinite Growth

- .vscode/settings.json
- SpellActivationOverlay.lua
- SpellActivationOverlay.toc
- changelog.md
- classes/deathknight.lua
- classes/druid.lua
- classes/hunter.lua
- classes/mage.lua
- classes/paladin.lua
- classes/priest.lua
- classes/rogue.lua
- classes/shaman.lua
- classes/warlock.lua
- classes/warrior.lua
- components/aura.lua
- components/glow.lua
- components/overlay.lua
- options/InterfaceOptionsPanels.lua
- options/InterfaceOptionsPanels.xml
- options/classoptions.lua
- options/db.lua
- options/defaults.lua
- options/glowoptions.lua
- options/overlayoptions.lua
Sequel of #87.
Implements #69.
Fixes #88.
Fixes #89.
> Overlay Class Options

- changelog.md
Includes changes for elunes-wrath branch, but also from the previous PR of hot-streak-heating-up from #112
> ChangeLog for Release 0.8.4

- .vscode/settings.json
- SpellActivationOverlay.toc
- changelog.md
- classes/warrior.lua
- components/util.lua
- options/defaults.lua
- options/glowoptions.lua
> Empowered Overpower

- changelog.md
- classes/warrior.lua
- options/defaults.lua
> Revenge of the Revenge

- .vscode/settings.json
- changelog.md
- classes/warrior.lua
- options/defaults.lua
> Execute Execute

- .vscode/settings.json
- classes/warlock.lua
- classes/warrior.lua
- components/util.lua
- options/classoptions.lua
- options/db.lua
- options/defaults.lua
- options/glowoptions.lua
- options/variants.lua
Implements and closes #125.
Implements and closes #126.
> Glowing Variants

- classes/warlock.lua
- classes/warrior.lua
- components/util.lua
> Revenge Setback

- changelog.md
- classes/mage.lua
- options/db.lua
- options/defaults.lua
> Era of Mages

- .vscode/settings.json
- SpellActivationOverlay.toc
- changelog.md
- options/InterfaceOptionsPanels.lua
The Trial of the Grand Crusader patch introduced the WoW 10.0 settings UI.
This Pull Requests does not rework setting entirely to the new system, but at least tries to keep things compatible.
Please note that Classic Era, which does not use the new settings UI, should unaffected by this update.
> Settings 10

- changelog.md
- classes/warrior.lua
- options/defaults.lua
> Warrior DPS T10 4p set bonus

- README.md
- SpellActivationOverlay.toc
- _curse/release_notes.html
- changelog.md
- classes/hunter.lua
- options/defaults.lua
> Mongoose Bite

- components/glow.lua
This will add support for the custom UI AzeriteUI5 and its custom version of LibActionButton.
> add support for AzeriteUI5's LibActionButton

- SpellActivationOverlay.toc
- changelog.md
- components/util.lua
- options/defaults.lua
> Fix stackable auras

- SpellActivationOverlay.toc
- changelog.md
- classes/mage.lua
- options/defaults.lua
Implements #179.
Small improvements to #172.
> Missile Barrage SoD

- changelog.md
- classes/shaman.lua
- options/defaults.lua
Minor changes to finalize #184
> Shaman SoD phase 2

- changelog.md
- classes/warrior.lua
> Bloodsurge SoD

- changelog.md
- classes/druid.lua
> Druid's updateSAOTimers now supports SoD

- _script/package.sh
- changelog.md
- classes/priest.lua
- options/defaults.lua
> Support for Priest's Surge of Light (SoD)

- options/defaults.lua
> Druid's Eclipse (SoD) is now explicitly enabled

- classes/paladin.lua
> Move Wrath paladin code out of reach of SoD

- changelog.md
- options/defaults.lua
Adds missing default settings for #206.
> Deep Freeze Followup

- changelog.md
- components/counter.lua
> Unlearn Counter

- changelog.md
- classes/paladin.lua
- components/rune.lua
- options/defaults.lua
> Divine Storm

- changelog.md
- classes/warrior.lua
- components/spell.lua
> Support for Warrior's Taste for Blood (SoD)

- _script/package.sh
- changelog.md
- classes/hunter.lua
- options/defaults.lua
Implements #226 but without Glowing Buttons, because there are way too many buttons to suggest.
> Lock and Load (SoD)

- changelog.md
- classes/druid.lua
- options/InterfaceOptionsPanels.lua
- options/defaults.lua
> Druid (Cata)

- changelog.md
- classes/warlock.lua
- options/glowoptions.lua
- options/overlayoptions.lua
- options/variants.lua
> Drain Soul specializations

- SpellActivationOverlay.lua
- changelog.md
> Do not play Sound on Spell Alerts without Pulse

- changelog.md
- classes/mage.lua
> Fix texture orientation for Mages (Cata)

- changelog.md
- classes/priest.lua
- options/db.lua
- options/defaults.lua
- options/overlayoptions.lua
- options/variants.lua
Partially implements #261.
Fixes #262.
> Priest (Cata)

- SpellActivationOverlay.lua
- changelog.md
- classes/shaman.lua
- components/effect.lua
- components/events.lua
> Followup of Shaman (Cata)

- changelog.md
- classes/warlock.lua
- components/effect.lua
- options/defaults.lua
- options/glowoptions.lua
- options/overlayoptions.lua
Implements #269.
Improves #238.
> Warlock (Cata)

- .vscode/settings.json
- SpellActivationOverlay.lua
- changelog.md
- classes/hunter.lua
- classes/shaman.lua
- classes/warrior.lua
- components/effect.lua
- options/defaults.lua
> Warrior (Cata)

- changelog.md
- classes/mage.lua
> Pyroblast! no longer triggers Heating Up

- changelog.md
- classes/priest.lua
- components/effect.lua
- options/db.lua
- options/defaults.lua
Also base Surge of Light glowing button of Flash Heal ability that costs no mana, even if it introduces a bug (#293).
> Support for Priest's Mind Melt (Cata)

- changelog.md
- classes/mage.lua
> Arcane Missiles Refresh

- changelog.md
- classes/mage.lua
> Impact requires Fire Blast to be usable

- changelog.md
- classes/mage.lua
> New Hot Streak (SoD)

- SpellActivationOverlay.toc
- _script/package.sh
- changelog.md
- classes/warlock.lua
- components/rune.lua
- options/defaults.lua
- variables/talent.lua
> Warlock SoD Phase 4

- _script/package.sh
- changelog.md
- classes/warrior.lua
- options/defaults.lua
> Warrior SoD phase 4

- SpellActivationOverlay.toc
- _script/package.sh
- changelog.md
- options/InterfaceOptionsPanels.lua
- options/InterfaceOptionsPanels.xml
- options/fix/Backdrop.lua
- options/fix/SharedUIPanelTemplates.xml
> Slider Fix Era

- classes/priest.lua
> Added Binding Heal for SoD

- components/bucket.lua
- components/events.lua
- options/overlayoptions.lua
- options/variables.lua
> Bucket Index Spell Name

- changelog.md
- classes/hunter.lua
- options/defaults.lua
> Burning Adrenaline

- changelog.md
- classes/paladin.lua
- classes/warrior.lua
> Option Subtext

- SpellActivationOverlay.lua
- classes/mage.lua
- components/sound.lua
- options/db.lua
- options/defaults.lua
Quick fixes before the release of v2.4.1
> Pre 2.4.1 fixes

- SpellActivationOverlay.toc
- _draft/misc.lua.txt
- components/trigger.lua
- variables/stance.lua
See GitHub issue #373 for more details.
Implements and closes #243.
> Add the 'stance' variable

- SpellActivationOverlay.toc
- _draft/releasenotes/release-2.4.2.md
- changelog.md
- components/glow.lua
> Native Glow Conflict

- _draft/releasenotes/release-2.4.2.md
- changelog.md
- classes/shaman.lua
- components/glow.lua
- options/defaults.lua
> Shaman MoP Followup

- SpellActivationOverlay.lua
- _draft/releasenotes/release-2.4.4.md
- changelog.md
- classes/priest.lua
- components/glow.lua
Fixes intended to prepare the release of v2.4.4, but after careful consideration, the version will jump to 2.5
> Pre-244 Fixes

- classes/mage.lua
- options/defaults.lua
I'm very much new to working on addons and lua, but hoping this is helpful for mages.
> add support for MoP mage spells

- SpellActivationOverlay.lua
- components/display.lua
- components/effect.lua
- components/overlay.lua
- options/InterfaceOptionsPanels.lua
- options/overlayoptions.lua
> Overlay Overlap

- SpellActivationOverlay.toc
- _draft/releasenotes/release-2.5.6.md
- _script/package.sh
- changelog.md
- classes/paladin.lua
- components/rune.lua
- components/spell.lua
- options/defaults.lua
> Pre 2.5.6 fixes
